#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
clear='\033[0m'
bg_red='\033[0;41m'
bold=$(tput bold)
normal=$(tput sgr0)

if [ "$branch" = "main" ]; then
  echo '\n'
  echo '\n'
  printf "${bold} ${bg_red}Branch [$branch] can only be modified through pull requests.${clear}${normal}"
  echo '\n'
  echo '\n'
  exit 1
fi

sh hooks/pre-push